# Generated by Django 6.0.2 on 2026-02-10 15:37

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the event')),
                ('date', models.DateTimeField(db_index=True, help_text='Event start date and time')),
                ('end_date', models.DateTimeField(blank=True, help_text='Event end date and time (optional)', null=True)),
                ('venue', models.CharField(help_text='Event venue/location', max_length=300)),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of participants', validators=[django.core.validators.MinValueValidator(1)])),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, help_text='Registration fee in INR (0 for free events)', max_digits=10)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether the event is open for registration')),
                ('image_url', models.URLField(blank=True, help_text='URL to event banner/image', max_length=500, null=True)),
                ('contact_email', models.EmailField(blank=True, help_text='Contact email for event queries', max_length=254)),
                ('payment_form_url', models.URLField(blank=True, help_text='Google Form URL for payment proof submission', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', 'is_active'], name='events_date_038412_idx'), models.Index(fields=['created_at'], name='events_created_9e2206_idx')],
            },
        ),
    ]
