# Generated by Django 6.0.2 on 2026-02-10 15:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_proof_url', models.URLField(blank=True, help_text='URL to payment proof (Google Drive link, etc.)', max_length=500, null=True, validators=[django.core.validators.URLValidator()])),
                ('transaction_id', models.CharField(blank=True, help_text='Payment transaction ID/reference number', max_length=100, null=True)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Payment Verified'), ('REJECTED', 'Payment Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes about the registration/payment')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, help_text='Admin who verified/rejected the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(help_text='Action performed (CREATED, STATUS_CHANGED, etc.)', max_length=50)),
                ('old_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_actions', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='registrations.registration')),
            ],
            options={
                'db_table': 'registration_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['user', 'event'], name='registratio_user_id_bfff7a_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['payment_status'], name='registratio_payment_76f062_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['created_at'], name='registratio_created_337c0c_idx'),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('user', 'event'), name='unique_user_event_registration'),
        ),
    ]
